DEFAULT_CONFIG = {
    "GreedAndFearLimit": 10,
    "ReverseTrendCheckBackSeconds": 600,
    "ReverseTrendCheckMinCount": 60,
    "SantimentThreshold": 1.0,
    "ReverseTrendCheckPercentageAgreeThreshold": 100,
    "SantimentFromTimeDaysAgo": 36,
    "SantimentToTimeDaysAgo": 30,
    "SantimentThresholdLong": 0.25,
    "SantimentThresholdShort": -0.25,
    "ReturnOnInvest": 0.08,
    "ReverseTrendCheckBackSeconds": 600,
    "ReverseTrendCheckMinCount": 60,
    "ReverseTrendCheckAllNegative": "true",
    "ReverseTrendCheckFirstGreater": "true",
    "ReverseTrendCheckLinearDecreasing": "true",
    "ReverseTrendLinearDecreasingThresholdPercent": 5,
}
