name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Unlock secrets
    #   uses: sliteteam/github-action-git-crypt-unlock@1.2.0
    #   env:
    #     GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Extract short commit SHA
    - name: Set short commit SHA
      id: vars
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Get Unix Timestamp
      id: timestamp
      run: echo "ts=$(date +%s)" >> "$GITHUB_ENV"

    - name: Set Repository Name to Lowercase
      run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Get Branch Name
      id: config
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        if [ "$BRANCH_NAME" = "main" ]; then
          TAG=latest
          echo "develop=" >> $GITHUB_OUTPUT
        else
          TAG=$BRANCH_NAME
          echo "develop=-$BRANCH_NAME" >> $GITHUB_OUTPUT
        fi
        echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Build and push for multiple architectures
      uses: docker/build-push-action@v4
      with:
        context: app
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/${{ env.REPO_NAME }}/bias:v1.${{ github.run_number }}_${{ env.SHORT_SHA }}${{ steps.config.outputs.develop }}
          ghcr.io/${{ env.REPO_NAME }}/bias:${{ steps.config.outputs.tag }}
          europe-west1-docker.pkg.dev/gcp-nuke/gcp-nuke/freqtradeorg/freqtrade/bias:${{ steps.config.outputs.tag }}

    - name: login GCP
      id: gcp
      run: echo ya29.a0AZYkNZgQe6LBXp9Eb2d-IuhKb_8TRLu_Ljyzrt6hLbzjUoI2QZmcQPHafJKMyRg0xp_yTlgu_Robxi5siUjOJGrl0kvFGOnuGdoYI5IP_N4XGSfyv94Bweu9aYhGYLXlCL4NmEn9EtiKO_VztbWxTy7zVlYNZDMkqGCJFNriZpQxr86OaCgYKAcYSARASFQHGX2Mi7ODaWIWMy4rwfOfaV0yteA0183 | docker login -u oauth2accesstoken --password-stdin https://gcr.io

    - name: Tag GCP
      id: gcptag
      run: docker tag ghcr.io/${{ env.REPO_NAME }}/bias:${{ steps.config.outputs.tag }} europe-west1-docker.pkg.dev/gcp-nuke/gcp-nuke/freqtradeorg/freqtrade/bias:${{ steps.config.outputs.tag }}

    - name: Push to GCP
      uses: docker/build-push-action@v4
      with:
        context: app
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          europe-west1-docker.pkg.dev/gcp-nuke/gcp-nuke/freqtradeorg/freqtrade/bias:${{ steps.config.outputs.tag }}
          
